on:
  release:
    types: [published]
    
# Zips the profile and uploads to the vatsys ftp server
name: Publish Profile
jobs:
  zip-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'profile.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.md'
    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v4.9
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://ftp.sawbe.com/${{ steps.branch-name.outputs.ref_branch }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
